name: Release

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub.
        uses: docker/login-action@v2
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: vars
        run: echo "version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT

      - name: Build and push the Docker image.
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
          context: .
          push: true
          tags: |
            dcjulian29/dokuwiki:${{ steps.vars.outputs.version }}
            dcjulian29/dokuwiki:latest
